### ISSUE TITLE
Not able to run the application for iOS

### ISSUE THREAD

**Issue by Shivakumar10101** [eggnstone/eggnstone_amazon_chime#12]
I'm integration this in Flutter, not able to run the application in iOS. I'm attaching the issue here. Please help
<img width="938" alt="Screenshot 2020-09-18 at 5 51 33 PM" src="https://user-images.githubusercontent.com/50594182/93596994-edbb9580-f9d7-11ea-9400-6d44d3e166f3.png">

**Comment by eggnstone** [comment]
Is the issue fixed with the current release?

**Comment by eggnstone** [comment]
Closing because no feedback and others are able to use it.
