### ISSUE TITLE
Video Tile Observer is Not Working & User Video is not binding

### ISSUE THREAD

**Issue by mohit67890** [eggnstone/eggnstone_amazon_chime#16]
Hi, I'm trying to the test and integrate the chime SDK, wherein it is working on the android phone and the voice is being accurately heard on the different platform (which is web SDK in this case).
However, my video from the smartphone is not visible on the web app, also the flutter app is unable to get Video Tile Observers event, whenever I switch on / off the video from the web app. 

Request you to help in the above problem.

Regards,
Mohit

**Comment by eggnstone** [comment]
Did you try the example? Does that work with the video tiles?
