### ISSUE TITLE
Module Compilation Error

### ISSUE THREAD

**Issue by mohit67890** [eggnstone/eggnstone_amazon_chime#17]
Hi, I'm trying to add the fluter plugin with stated steps in the readme file. 
However, I'm getting module compilation error. Exact Error is produced below:

_Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3 compiler: /Users/mohitgarg/Documents/koach/koach/ios/.symlinks/plugins/eggnstone_amazon_chime/ios/AmazonChimeSDK.framework/Modules/AmazonChimeSDK.swiftmodule/arm64-apple-ios.swiftmodule_

I'm using Xcode Version 12.1 and the iOS is 14.1 on iPhone X.

**Comment by eggnstone** [comment]
Does this problem still persist?

**Comment by eggnstone** [comment]
Closed due to no feedback.
Please feel free to reopen.

**Comment by gianlucainnocente** [comment]
Hello, we have the same problem
