### ISSUE TITLE
What's the Road Map for the Web implementation?

### ISSUE THREAD

**Issue by xni06** [eggnstone/eggnstone_amazon_chime#18]
Currently, the README states that Web is in a state of TODO - do you have a Road Map for this feature?

**Comment by eggnstone** [comment]
I'm open to pull requests but I personally am not working on it nor plan to do so right now.

**Comment by xni06** [comment]
> I'm open to pull requests but I personally am not working on it nor plan to do so right now.

No problem - thanks for the update
