### ISSUE TITLE
iOS video tile convert to json not included width and height

### ISSUE THREAD

**Issue by EthanJhou** [eggnstone/eggnstone_amazon_chime#19]
The function convertVideoTileStateToJson in ChimeVideoTileObserver doesn't contain VideoStreamContentHeight and VideoStreamContentWidth.

**Comment by eggnstone** [comment]
I added the required lines of code but don't have an iOS test system handy.
Is the Issue fixed?

**Comment by EthanJhou** [comment]
Yes.
Thanks.
