### ISSUE TITLE
Initial setup of project

### ISSUE THREAD

**Issue by henlamk** [eggnstone/eggnstone_amazon_chime#2]
I seem to be struggling with getting the MethodChannel and EventChannel working properly.

After having set up a test plugin which works without any issue I am wondering how you set up the project to begin with. 

Things I have tried: 
- delete /ios
- flutter create . (recreates /ios with different names, e.g. EggnstoneAmazonChimePlugin and not ChimePlugin)

**Comment by eggnstone** [comment]
I think I used
`flutter create -t plugin --org dev.eggnstone --project-name chime eggnstone_amazon_chime`
I didn't want that long name for the plugin.
After the creation I did not make any changes to the iOS part.

**Comment by henlamk** [comment]
I have set up a project just like that to check if any similar issues appear, without success (meaning that it worked). 
I know it is exhausting but would you kindly set up the project once again to have a clean start?
Though I am sure to find what's wrong with it eventually, it might very likely end in a mess for the ios side of things.

**Comment by eggnstone** [comment]
What do you mean to set up the project again? Delete the whole repository and start from scratch?
I am optimistic we can figure it out together. I created a new branch "iOS-Integration". Can you send a pull request for your iOS part? I do have a macOS VM so I could compile the code and do some basic tests. I'm just not an experienced iOS developer.

**Comment by eggnstone** [comment]
By the way you can reach me via the email given on this page: https://pub.dev/publishers/eggnstone.dev/packages
