### ISSUE TITLE
Android/iOS SDKs are out of date

### ISSUE THREAD

**Issue by xni06** [eggnstone/eggnstone_amazon_chime#20]
The Android/iOS SDKs referenced in the README are from October 2020 - how frequent will this library be updated to keep aligned with the parent libraries?

- amazon-chime-sdk-0.7.4.tar.gz but latest is 0.11.2
- amazon-chime-sdk-0.11.1.tar.gz but latest is 0.16.1

**Comment by eggnstone** [comment]
I'm not actively watching for new releases.
Are there any bugs the new release fixes or any new features?
The thing is I need to unzip these files and zip them into one file in a specific way/order, so that a slightly annoying task.

**Comment by xni06** [comment]
>The thing is I need to unzip these files and zip them into one file in a specific way/order, so that a slightly annoying task.

Could you document this task? The community would then be able to do it and submit a pull request.

**Comment by eggnstone** [comment]
* Android SDK is up to date: v0.11.2
* Added instructions on how to create amazon-chime-sdk-combined-without-libc++_shared.so.aar.

I'm not sure I would be OK with accepting pull-requests for that library file though. It might potentially contain malicious code I would then be distributing. It's faster to perform the manual build steps than to check if the library file is OK.

**Comment by xni06** [comment]
>I'm not sure I would be OK with accepting pull-requests for that library file though. It might potentially contain malicious code I would then be distributing. It's faster to perform the manual build steps than to check if the library file is OK.

Fair enough, thanks.

However, if the steps were documented, if we came across a problem we could fork the repo and apply the library updates locally to see if it fixes the problem - we could then report the problem back to you to update the library yourself or continue with our fork in the meantime. We just need to make sure that we create the libraries the same way that you do.

**Comment by eggnstone** [comment]
> However, if the steps were documented, if we came across a problem we could fork the repo and apply the library updates locally to see if it fixes the problem - we could then report the problem back to you to update the library yourself or continue with our fork in the meantime. We just need to make sure that we create the libraries the same way that you do.

Agreed. Please check out the new file:
`How to combine amazon-chime-sdk and amazon-chime-sdk-media.md`
Does it suffice?

**Comment by xni06** [comment]
>Does it suffice?
Perfect, thanks!

Just a typo though - need a space after the hashes as does not render correctly:

`###Note "Zip contents" means to go into that directory and zip all files there.`

**Comment by eggnstone** [comment]
> Just a typo though - need a space after the hashes as does not render correctly:
Thanks. No-space wasn't on purpose and looked fine in WebStorm IDE but yeah, doesn't render properly in Github.
