### ISSUE TITLE
Execution failed for task eggnstone_amazon_chime:bundleDebugAar. Direct local .aar file dependencies are not supported when building an AAR.

### ISSUE THREAD

**Issue by AnanthiSubash** [eggnstone/eggnstone_amazon_chime#23]
I get this error when I tried installing in my app:

Execution failed for task ':eggnstone_amazon_chime:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be pac
kaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :egg
nstone_amazon_chime project caused this error: C:\Subash\software\flutter_windows_2.0.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\eggnstone_amazon_chime-1.0.2\android\amazon-chime-sdk\amazon-chime-sdk
-combined-without-libc++_shared.so.aar

**Comment by NatsuSalamada** [comment]
face the same issue.

**Comment by eggnstone** [comment]
I don't have a real solution but if you downgrade gradle then it works.

In `android/gradle/wrapper/gradle-wrapper.properties` use
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

In `android/build.gradle` use
`classpath 'com.android.tools.build:gradle:3.6.4'`

**Comment by eggnstone** [comment]
@AnanthiSubash @NatsuSalamada
Please check out version 2.0.2.
Please follow the changed instructions in the README.md.
Does this fix the problem?
