### ISSUE TITLE
Where to put serverless app URL?

### ISSUE THREAD

**Issue by sultankh18** [eggnstone/eggnstone_amazon_chime#9]
Hi, I've implemented Amazon Chime on native android using their Android SDK and demo application. In your demo code i can't figure out where to put the URL of the serverless app deployed on Cloud9. Also don't understand what the 4 URLs which you pass as parameters in the createMeetingSession method do.
A bit of help would be appreciated. Thank you.
![Capture](https://user-images.githubusercontent.com/68068566/90770249-ec307c00-e30a-11ea-8d4b-11a352fc4816.PNG)

**Comment by eggnstone** [comment]
I haven't used the serverless app yet. How do you create a session with it?

The mediaplacement URLs probably point to the servers that handle the audio and video streams.
All that data is what you get when you create a meeting and then an attendee.

**Comment by sultankh18** [comment]
When implementing the native android SDK for chime one of the prerequisites is to deploy the Amazon Javascript SDK provided by Amazon here [https://github.com/aws/amazon-chime-sdk-js] as a serverless application on a Cloud9 enviornment using your IAM user.
The URL is then put in the string resources of the native android demo application and used to create a meeting session.

**Comment by sultankh18** [comment]
Can you please give an example of the meeting data which we should put here (authentic data and not dummy values)
`// Copy the file MeetingSessionCreator.dart.template to MeetingSessionCreator.dart.
            // Adjust MeetingSessionCreator to supply your proper authenticated meeting data.
            // (You can leave the dummy values but you will not be able to join a real meeting.)
            // This requires you to have an AWS account and Chime being set up there.
            // MeetingSessionCreator.dart is to be ignored by git so that your private data never gets committed.
            meetingSessionState = await MeetingSessionCreator().create();`

**Comment by eggnstone** [comment]
What does the function joinMeeting return? Can you give an example?

>P.S. are you implying that this library does not allow the user to start a meeting but only join a meeting already created?
Correct. The client SDK has no AWS credentials and therefore cannot create meetings that would cost you money, otherwise anyone using your app could create private meetings costing your money.
You therefore need a server app that creates meetings and attendees and then sends the details including the jointoken to the client so that the client then using this data can join.

**Comment by eggnstone** [comment]
Can we close this issue?
